########################### SERVICES
services:
  ########################### JENKINS
  jenkins:
    image: jenkins
    container_name: jenkins    
    build:
      context: ./
      dockerfile: Dockerfile-jenkins
    restart: unless-stopped
    command: # CLI arguments
      - "--prefix=/jenkins"
    labels: # Configs for traefik
      - "traefik.enable=true"      
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
    ports:
      - 8081:8080
      - 50000:50000   
    networks:
      - web
    environment:        
      - TZ=America/Sao_Paulo      
    volumes:
      - "./appdata/jenkins:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - "./appdata/jenkins_tmp:/tmp"

########################### NETWORKS    
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true
