create table tb_category (
                             id bigint generated by default as identity,
                             name varchar(50) not null,
                             primary key (id)
);
create table tb_user (
                         id bigint generated by default as identity,
                         display_name varchar(255),
                         password varchar(255),
                         username varchar(255),
                         primary key (id)
);

create table tb_product (
                            id bigint generated by default as identity,
                            description varchar(1024) not null,
                            name varchar(100) not null,
                            price double not null,
                            category_id bigint not null,
                            created_by_id bigint not null,
                            modified_by_id bigint not null,
                            created_date timestamp not null,
                            modified_date timestamp not null,
                            primary key (id)
);



alter table tb_product add constraint FK_Category_Product
    foreign key (category_id) references tb_category;
alter table tb_product add constraint FK_User_CreatedBy_Product
    foreign key (created_by_id) references tb_user;
alter table tb_product add constraint FK_User_ModifiedBy_Product
    foreign key (modified_by_id) references tb_user;

create table tb_authority (
                              id bigint generated by default as identity,
                              authority varchar(50),
                              primary key (id)
);

create table tb_user_authorities (
                                     user_id bigint,
                                     authority_id bigint
);
alter table tb_user_authorities add constraint FK_User_User_Authorities
    foreign key (user_id) references tb_user;
alter table tb_user_authorities add constraint FK_Authority_User_Authorities
    foreign key (authority_id) references tb_authority;